title: Mohammed EL-KHOU
logo: /assets/img/m.elkhou.svg
description: Ph.D. C.V. USMBA | Junior Data Science | Artificial Intelligence | Computer Vision Engineer 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
